### PR TITLE
LEET-286

### PR DESCRIPTION
**Pull request by Ebenezer-ebu**
## What
- UI design for order details page

### CODE REVIEW

**Comment by chiomaT** [comment]
The ticket number should be written as it is in the ticket e.g LEET-286

**Comment by Ebenezer-ebu** [comment]
I have edited as recommended

**Comment by chiomaT** [comment]
Hi Eben. styles are being done a styles.ts file you'd create you can check other component just for uniformity. and secondly there's a Fonts component we use for all typograpghy, all you need to do is to specify the type of typography. e.g <Fonts type='small_text'>{children}<Fonts>. Thank you.

**Comment by Ebenezer-ebu** [comment]
I have made all possible adjustments

**Review by chiomaT — APPROVED** [review]

**Pull request merged**
